services:
  - type: web
    name: n8n-personal
    runtime: image
    image:
      url: n8nio/n8n:latest
    plan: free
    envVars:
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: n8n-personal-m51h.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-personal-m51h.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-personal-m51h.onrender.com
      - key: GENERIC_TIMEZONE
        value: Europe/Rome
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
      - key: EXECUTIONS_DATA_MAX_AGE
        value: "168"
      - key: N8N_PAYLOAD_SIZE_MAX
        value: "16"
      - key: N8N_METRICS
        value: "false"