services:
  - type: web
    name: n8n-personal
    runtime: image
    image:
      url: n8nio/n8n:latest
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        sync: false
      - key: N8N_EDITOR_BASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: N8N_METRICS
        value: "false"
      - key: N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN
        value: "true"
      - key: DB_TYPE
        value: sqlite
      - key: DB_SQLITE_DATABASE
        value: /home/node/.n8n/database.sqlite
      - key: GENERIC_TIMEZONE
        value: Europe/Rome
